require("packer_plugins")

require("plugins/nvim-tree")
require("plugins/nvim-web-devicons")
require("plugins/lualine")
require("plugins/gitsigns")
require("plugins/twilight")
require("plugins/nvim-cmp")
require("plugins/nvim-autopairs")
require("plugins/nvim-lspsaga")
require("plugins/gotests")
require("plugins/treesitter")
require("plugins/nvim-scrollbar")
require("plugins/conform")
require("plugins/comment")
require("plugins/codecompanion")

require("core/settings")
require("core/keymaps")
